# Generated by Django 5.0.6 on 2024-08-02 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0002_alter_phone_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='image',
            field=models.URLField(verbose_name='Изображение'),
        ),
    ]
